### ISSUE TITLE
Add DNS Probe support for DNS query monitoring

### ISSUE THREAD

**Issue by servak** [servak/mping#37]
## Summary
Add DNS probe functionality to enable DNS query monitoring and validation for network engineers. This feature will help monitor DNS server availability, response times, and record validation.

## Motivation
DNS monitoring is critical for network engineers to:
- Monitor DNS server availability and response times
- Validate DNS record resolution (A, AAAA, MX, etc.)
- Detect DNS resolution failures and timeouts
- Monitor public DNS servers (8.8.8.8, 1.1.1.1, etc.)
- Troubleshoot DNS-related network issues

### Target Format
```bash
mping dns://8.8.8.8/google.com           # A record query
mping dns://1.1.1.1/example.com/MX       # MX record query
mping dns://dns-server:53/domain.com/AAAA # AAAA record query
```

### Features
- DNS query response time measurement
- Support for common record types (A, AAAA, MX, CNAME, TXT, NS)
- Configurable DNS server and port (default: 53)
- Query timeout handling
- Response validation (record exists/not found)
- Integration with existing TUI display

### Technical Requirements
- Implement `DNSProber` following existing `Prober` interface
- Add `DNSConfig` for DNS-specific configuration
- Use standard DNS library (e.g., `github.com/miekg/dns`)
- Support both UDP and TCP DNS queries
- Integrate with existing event system and metrics collection
- Add configuration options in YAML config file

### Configuration Example
```yaml
prober:
  dns:
    probe: dns
    dns:
      server: "8.8.8.8"      # Default DNS server
      port: 53               # Default DNS port
      record_type: "A"       # Default record type
      use_tcp: false         # Use TCP instead of UDP
      timeout: 5000ms        # Query timeout
```

### Acceptance Criteria
- [ ] DNS queries can be performed against specified servers
- [ ] Query response time is measured and reported
- [ ] Multiple record types are supported (A, AAAA, MX, CNAME, etc.)
- [ ] Timeout and resolution failures are properly handled
- [ ] Both UDP and TCP protocols are supported
- [ ] Integration with existing TUI works correctly
- [ ] Configuration is properly loaded from YAML
- [ ] Unit tests are implemented
- [ ] Documentation is updated

## Implementation Notes
- Follow existing probe architecture and patterns
- Handle DNS response codes properly (NOERROR, NXDOMAIN, SERVFAIL, etc.)
- Consider caching for performance optimization
- Ensure thread-safe operation for concurrent queries
- Support both IPv4 and IPv6 DNS servers

## Priority
**High** - DNS monitoring is fundamental for network troubleshooting and infrastructure monitoring.

## Dependencies
- Consider adding `github.com/miekg/dns` library for DNS operations
